# Generated by Django 5.0.2 on 2024-02-14 21:34


from django.db import migrations
from django.db import models

import src.core.models.transactions


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('nodes', models.JSONField(default=src.core.models.transactions.create_initial_nodes)),
                ('logs', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
